"""adding lang and home columns

Revision ID: 4f99cea44e83
Revises: 3d24e72bbf56
Create Date: 2024-11-17 14:46:14.679172

"""
from alembic import op
import sqlalchemy as sa


import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")
schema = SCHEMA if environment == "production" else None
# revision identifiers, used by Alembic.
revision = '4f99cea44e83'
down_revision = '3d24e72bbf56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=schema) as batch_op:
        batch_op.add_column(sa.Column('lang', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('for_home', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=schema) as batch_op:
        batch_op.drop_column('for_home')
        batch_op.drop_column('lang')

    # ### end Alembic commands ###
