"""adding primary key to role

Revision ID: 778969b20414
Revises: 92e2fc4f0473
Create Date: 2024-10-22 17:26:55.359845

"""
from alembic import op
import sqlalchemy as sa


import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

schema = SCHEMA if environment == "production" else None
# revision identifiers, used by Alembic.
revision = '778969b20414'
down_revision = '92e2fc4f0473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=schema) as batch_op:
        batch_op.create_unique_constraint('uq_first_last_name', ['first_name', 'last_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('artists', schema=schema) as batch_op:
        batch_op.drop_constraint('uq_first_last_name', type_='unique')

    # ### end Alembic commands ###
